/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.discovery.jsonc --include-runtime=false --env-interface=DiscoveryWorkerEnv discovery-worker-env.d.ts` (hash: 7a6592ded4ebbd66ff47490c519224ab)
interface __BaseEnv_DiscoveryWorkerEnv {
	DB: D1Database;
	TINYFISH_API_KEY: string;
	CRON_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/discovery");
	}
	interface Env extends __BaseEnv_DiscoveryWorkerEnv {}
}
interface DiscoveryWorkerEnv extends __BaseEnv_DiscoveryWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TINYFISH_API_KEY" | "CRON_SECRET">> {}
}
